language: node_js
node_js:
- '8'
env:
  global:
  - REACT_APP_RELEASE=$TRAVIS_COMMIT
  - HEROKU_APP_ID=sentry-demos-react
  - SENTRY_ORG=testorg-az
  - SENTRY_PROJECT=sentry-demos-react
  - secure: p2OkLEcyf7z4TQyPAzJiyjoR4SdyavT7/bmIKEtpNtAj2otiU6wIyBoKZ7MjOEUxffcZzHEmP2+44u1x25Q7ozrH3PUHYxJkBWP+mQiZxtt+1J157q24r6+9WL6uaRVabwQhigPpRwXEntIvoJuAHgp+X1+TP/jWuux/yQA2SivEg/O7l2FqUqeBcXzUMLzEOP+pAx4NPVTAnguPnHsSwxIJw/W1C6lzqzxY4q1aysJbblHLKXnRhIHJSPBqxgYK8Db00gFKpSpzUCHMCFVlZURBw+OLA8Tih2LSLAZ7YfYQlVlu+vkMGuArJ2coE1drk3os/F+SbiJ8rNhqi3wnvZUf9Muf0lPRjuB70xlD8jM6J+lWYhqABsCx3UvWNN7cmKXxb+xtvWZT1ItbVMeVq17OT1v7UdfbsRp6Z2keo2ctjj041s9t54Qen+PsM5oczpXyDxRJt7j8CzTvrWUMJXEobhxTkcV0vULIzpeWB1KzE2TXK6gguTJdDVAAESACB9LJ2Lq+cDFrLbBzdk97rjpfcCEfRPQkLXA4Qoft7yFu6Nuu0zmA+jeczaPXNpSNegBg/YMHoTTKIrDYZNTqgJR7E9JUki3WA2ByBRvR8Eo9xgkRjrpYfAI9KW58ZiWDcoSsXKtLyVDRQUkfIczsuTSog2uD3roRDO3i2mBMfvg=
  - secure: jlypOnANosRmMfrRFV/4CNfg2hMUy7TK9ln5UXixlbtyVTgV3E9AH948HVP0nsUbf2m7y0P3BFsPwNCqyeFEhwK51QMevENIMzNroL8FLL/wykoRPmb731mV2afT4b02IHiXT4aqe3YUPhIZwDkVeGv0i8L2FPw5zihhP+cF/5MvSxSa8ourMkLN2cBdPK26NyyiYwCK71cRaU3a4ivmC2hy3BNMa4HoX6KtYCulmH9RExE9lp9fq68CCByqpuRPM/2pOB0Szcx21yIWwuyRLJdBBAkZ9TkPanne5w+ZdVF4v338zrPyfpuVaG0si0Dy7JI4npHWMMYSND9iUtePkcUHnRy79sYYXO0RbXX9pLs9sZhQ5T8+NWbItKpbP26gJomkT27BLrqebxUEi7fnV7qtvY2IuEBOcVDgz58ROIL1r8TQ/zxZysPj8SG656P4xf/g8LJSFJpGdt7tFBY9MBIawJL/um0BC0GZ2ybazy6SGu4XzQOIy0ycOuRqlhp08NHCfmbXRtgRSoXNujudaRQARDiGoJOe2UqRljr9yfD+c1SQcCUJWep/IycuMQqr18nF2urZv3EmkZo9MrAqmaP/3kzy6DLI6pyU/gsEv4SbTEjjSUTQGJ6Q1/cOCmQTi5DN9/NnhoIDL722l6bp8T4P5GPwYKWn6LylBbKZ7eI=
before_install:
- npm install -g sentry-cli-binary
deploy:
  provider: heroku
  api_key:
    secure: y+OoPqaSWjFVoq8NoeudT1wFwTCFe3I/EHdfSIweKLPZdbaNa9qOa0y8OtxTZdn5cPuFvrA03OfZba1MY4MBOq+QIyp8z8MhgJFIIsW8eT+MIsdSo7fZBPzoAUz00+xARrl0bmYO4FsuBiXUh35VAV9nT0njHMC2TfIvga1oAH8pOrXcYhBOflNmViG1YxP7eAtIGM1TZx3c1tWp6n4mLdfFgXNOmbGmoTJ6gmVjHAVofcsg2TZxIgHsIctydTBfRsoOVnGKhdr6XLqHU6vkViC4NGA/9V48H2GHfHL6rgUkv+tVlkdrs9DQsRsjNNrBQGejKllRetHZxKGZFD4mxg5/MiIZbn9GnmncbPhokhnPO0OB7StKdvwMuyBV1OkB2rGVFxdhbooIzKlIPzOaSKiZuHO4PeFMnXmVzKFSSZpqhyM9EHXvrsG5UWkTEdTZIAoqn2xQ8cAozIVE0RY7t7Qx2X/XJIUpiE5RmnVbQv0x4h2tBLzJmIQEWZm8T2xP+nHCgwjZi6ZXcjA6My+6s2jwL5hUGZRJzBlgUwRkkRwUiHxXnXy/qnQeKrRtTjrN+mb+JGFTqB0xuxDYEx2keyNAwkmnMq2U36Myh9boo90H0eWC7NzQzAZ2gl+cowxS2eUtKb5/NzLWPZ/vhSUbYO2RGa28DlZspn6M3CP54fw=
  app: sentry-demos-react
  on:
    repo: sentry-demos/react
before_deploy:
- make setup_release set_release_context
